trigger:
  branches:
    include:
      - main
  
pr: none

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Install step"
    yarn
  displayName: Install
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Test and lint step"
    echo ">>> Linting"
    yarn lint
    echo ">>> Testing"
    yarn test:unit
  displayName: Run Tests and Lint
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Build step"
    echo ">>> Building"
    yarn compile
  displayName: Build
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Checking version"
    node ./check-version.js
  displayName: Version check
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Publish"
    yarn deploy
  displayName: Publish
  condition: succeeded()